### ISSUE TITLE
HateoasResourceService.searchCollection issue in angular route resolve

### ISSUE THREAD

**Issue by gguptha** [lagoshny/ngx-hateoas-client#111]
I have a method getUsers() which calls the searchCollection method of the HateoasResourceService.
```
@Injectable({
    providedIn: 'root'
})
export class PFUserService {

    constructor(private _userService: UserService, private _hateoasResourceService: HateoasResourceService, 
                private _authService: AuthService, private httpClient: HttpClient) { 
    }

    getUsers(): Observable<any> {
        console.log('in get users');
        return this._hateoasResourceService.searchCollection(UserResource, 'findByInstance', {
            params: {
                instance: sessionStorage.getItem('_instanceHref')
            }
        });
    }
}
```

I also have an initial data resolver defined below -
```
export const userListDataResolver = () => {
    const pfUserService = inject(PFUserService);
    console.log('in route resolver');
    return forkJoin([
        pfUserService.getUsers()
    ]);
}
```

Lastly I have the angular route defined below -
```
{
    path: 'users', 
    loadChildren: () => import('app/modules/admin/users/user-list/user-list.routes'),
    resolve: {
        initialData: userListDataResolver
    }
},
```

When the browser is redirected to page /users for the first time, the getUsers() method is executed and data is fetched after the api finishes execution (because of the route resolve configuration). Subsequently, whenever the browser is redirected to /users page, the _hateoasResourceService.searchCollection call is never executed. You can see both the console messages, one displayed int the resolver and one in the getUsers() method, but the _hateoasResourceService.searchCollection() method is not getting executed.

I am not sure if this is a bug. Please let me know if you need any further information.

**Comment by lagoshny** [comment]
Hello @gguptha ,

It seems that you don't see the second request in `_hateoasResourceService.searchCollection()` because after first request the result put to the cache and when request params is not changed the result gets from the cache for the second and futher requests.

By default, caching used for all GET requests, and If you want to disable caching for this request, you should pass `useCache: false` param in `searchCollection` method.
Also, you can disable caching for all requests using lib configuration param `CacheMode.ON_DEMAND` then cache will be used only when you pass `useCache: true` explicitly. More about cache configuration, see [here](https://github.com/lagoshny/ngx-hateoas-client#cache-params).

You can find more information about caching in [documentation](https://github.com/lagoshny/ngx-hateoas-client#cache-support).

**Comment by lagoshny** [comment]
@gguptha did it solve your problem?

**Comment by gguptha** [comment]
@lagoshny Yes it did. Thanks.
