### ISSUE TITLE
Support for Multiple REST Services

### ISSUE THREAD

**Issue by mathias-ewald** [lagoshny/ngx-hateoas-client#57]
Hi, I basically want to reopen #19 since I believe it might be a valid feature request.

Working on Kubernetes a lot, I am using Knative Serving to run the different microservices of my app. For every app that I deploy, Knative creates a `Route` - basically an external URL that can be used to access the microservice. With multiple microservices in place responsible for different thing and each one exposing a REST API, I find myself in the need to connect to multiple URLs from a single Angular app.

I seems to be such a common pattern to me and I find it hard to believe that everybody puts an API gateway in front of everything when there's not a lot more to gain than just unifying the APIs under a common hostname. 

Also, a frontend app might be aggregating information from different places that have nothing in common and might not even be under the control of the same organization. Would I need to write backend code to make them all accessible on the same hostname? It seems unnecessary to me.

**Comment by lagoshny** [comment]
Hi @mathias-ewald ,

I added possibility to use different URLs for resources.

It is available in `3.2.0` lib version for new Angular and `2.5.0` in old Angular.

In short you need to define your routes in lib configuration:

````ts
  constructor(hateoasConfig: NgxHateoasClientConfigurationService) {
    hateoasConfig.configure({
      http: {
        // Use this router name for default Resources route it will be applied to all Resources by default
        defaultRoute: {
            rootUrl: 'http://localhost:8080/api/v1'
        },
        anotherRoute: {
          rootUrl: 'http://localhost:9090/api/v1'
        }
      }
    });
  }
````

After that, you can specify route name in your Resource using new `ResourceOption` parameters in `@HateoasResource` decorator:

`````ts
@HateoasResource('resource1', { routeName: 'anotherRoute' })
export class Resource1 extends Resource {
  ...
}

@HateoasResource('resource2')
export class Resource2 extends Resource {
  ...
}
`````
In this case, `Resource1` will be use `anotherRoute` URL to retrieve Resource.  Resource2 will be use `defaultRoute` because you didn't specify any route name, default route will be used instead.


Read more about it in [documentation](https://github.com/lagoshny/ngx-hateoas-client#using-multiple-urls-to-retrieve-resources).
