### ISSUE TITLE
Numbers are converted to dates in 3.1.1

### ISSUE THREAD

**Issue by MichiOnGithub** [lagoshny/ngx-hateoas-client#58]
Hi, 

first of all thanks for this great library! 

After updating to 3.1.1 many number fields are converted into dates in our application. 
This probably has to do with [these changes](https://github.com/lagoshny/ngx-hateoas-client/pull/56/files) as `Date.parse()` accepts dates in several formats e.g. `YYYY` which would convert a value of '200' to a Date. A possible fix could be to check with `isNan()` if this is a number or a possible date string.  

I would also be very happy if there was some way to either configure/disable this behavior or if there was a way to set a date conversion strategy as many projects are using custom date library such as `momentjs`, `dayjs` and so on. 

Cheers,
Michi

**Comment by lagoshny** [comment]
Hi, thank you for the issue.

Yes, I see it. I'm already fixing it.

**Comment by lagoshny** [comment]
@MichiOnGithub fixed in new versions: `2.4.2` for old Angular and `3.1.2` for new Angular.

As you mentioned I added new config parameters to define date formats to parse, you can read about it in [documentation](https://github.com/lagoshny/ngx-hateoas-client#typesformat).

If no date formats defined or property does not match date format, then date will parse as before as raw string.

**Comment by MichiOnGithub** [comment]
@lagoshny thank you for your fast reply and for updating the library. I can confirm that the issue is fixed now :+1:
