### ISSUE TITLE
search page is forced to use cache

### ISSUE THREAD

**Issue by simonebracaloni** [lagoshny/ngx-hateoas-client#64]
SortedPageParam does not extend GetOptions, so the option useCache cannot be set to true
Is this by intention?

**Comment by lagoshny** [comment]
Hi,

Because cache support added later than `customPage` method and I wanted to set `useCache` as `true`  by default, I added `useCache` as optional param in `customPage` method.
Therefore, you can use `useCache ` as second param in `customPage` method. By default, `useCache` set `true`.

Why `SortedPageParam` does not extend `GetOptions`? I didn't think, that some params from `GetOptions` in `customPage` method needed. If even `SortedPageParam` will extend `GetOptions` then only params from `SortedPageParam` will be applied to the request, others will be ignored. 

But, If you need some extra params that `GetOptions` contains in `SortedPageParam`, write about it case. I will think about it.
